---
title: "An Analysis of the Premium Associated with Bitcoin"
author: | 
  | Jenna Christensen and Kai Jensen
  | ECON 4008-01: Macro Modeling
  | Department of Economics
  | St. Lawrence University
  | 23 Romoda Drive 
  | Canton, New York 13617
output:
  pdf_document: default
  word_document: default
keywords: Cryptocurrency, Equity Premium, Finance
abstract: |-
  Insert abstract here and then add JEL Codes   \par
---

#Introduction 

Nearly a decade ago, peer to peer payment networks and digital currencies were unknown to virtual communities and the general population. Cryptocurrencies including Bitcoin, LiteCoin, and DogeCoin became household names and grasped the attention of investors, analysts, and economists in 2016. Bitcoin’s anonymous users and encrypted transactions made it the most prominent of virtual currencies. At its inception, Bitcoin traded at 0.63 U.S. dollars per Bitcoin, and by 2014 its value peaked at 1,101.65 U.S. dollars per Bitcoin. By November 20, 2017, its price was recorded at a record high of $8,237.45 and increased over 111.19% in the 15 preceding weeks. However, its price today is less than half of that record value.  The fundamental determinants of Bitcoin’s price include supply and demand interactions, individuals’ expectations, and the development of technological instruments used for conducting Bitcoin transactions. 

Unlike standard fiat money, Bitcoin is not within the domain of central governments, authorities, or individuals. The supply and demand for most monetary units are driven by macroeconomic variables which include interest rates, inflation, and the actions taken by central authorities. However, significant changes in the price of Bitcoin are attributable to specific factors relating to cryptocurrencies. Since Bitcoin’s supply evolves according to a publicly known algorithm and is fairly inelastic, and the demand side of the market is mainly driven by the expectations of investors who plan on holding the currency and later selling it, Bitcoin has an exceptionally volatile behavior which makes it an extremely risky yet profitable investment. Its market performance includes steep increases and precipitous declines in value further suggesting the market is driven by the expectations of investors and spectators. 
 
This empirical work seeks to analyze the shock process of Bitcoin as well as the shock process of relatively risk free U.S. Treasury Bills (i.e. to answer the following question: What is the shock process of Bitcoin and the shock process of a relatively risk free U.S. Treasury Bill?). Furthermore, this study seeks to examine the risk aversion parameter necessary to generate the level of equity return observed in the historical price data of Bitcoin and U.S. Treasury Bills (i.e. to answer the following question: What is the risk aversion parameter necessary to generate the level of equity return observed in historical price data of Bitcoin and U.S. Treasury Bills?). Traditionally, studies that replicate the equity premium puzzle with a Lucas Asset Pricing Model examine the excess returns of a risky security or index relative to those of risk free assets or treasury bonds. Until 2016, cryptocurrencies were largely unacknowledged by academics. Although the volatile behavior of cryptocurrency is now at the forefront of many financial economic works, the risk premia necessary to hold cryptocurrencies are scantly studied. 

#Literature Review 

Robert Lucas (1978) examines the stochastic behavior of equilibrium prices in a
representative, pure exchange, single good economy with identical consumers.1 His paper first
examines the behavior of asset prices in a one-good pure exchange economy with identical
consumers and introduces a method of constructing equilibrium prices. Lucas later defines the
general equilibrium as a pair of functions: a price function and an optimum value function. To
reach a competitive equilibrium, all output must be consumed, all asset shares must be held, and
all asset prices must solve the dynamic program. Thus, the general equilibrium and market
clearing price for trees at time 𝑡 must satisfy the following *Insert Requirements* Hence, the equilibrium price of the asset must satisfy 𝑝 = 𝐸 {∑= 𝛽1 23(5678 ) 𝑑 } .2 Lusas' paper was the first of its kind to model risky asset ownership decisions and determine how risk premiums are incorporated in the price of an asset.

Subsequent to the publication of the Lucas Asset Pricing Model, Mehra and Prescott (1985) present the equity premium puzzle. They find that in a competitive pure exchange economy, the average annual yield of equity is, at most, four-tenths of a percent higher than that of short-term debt. In stark contrast, the historical yield observed by Mehra and Prescott has a premium of six percent when accounting for U.S. business cycle fluctuations and reasonable risk aversion levels. They conclude that the historical U.S. equity premium, the return earned by a risky security in excess of that earned by a relatively risk-free U.S. Treasury Bill, is not only irrational but also inexplicable. According to Nada (2013), the economies used in Mehra and Prescott’s study have a “stationary equilibrium for growth rate process on consumption as well as returns”. Nada maintains that the elasticity of substitution between consumption in time period 𝑡 and time period 𝑡 + 1 is sufficiently small to yield a six percent average premium, but the magnitude of
the covariance between the marginal utility of consumption and equity returns is not sufficiently large enough to justify the equity premium observed. Mehra and Prescott’s equity premium puzzle ignited an extensive research effort within the fields of macroeconomics and finance. A plethora of theoretical speculations and plausible explanations for this anomaly have been presented, but no single solution has been widely accepted by economists.

Traditionally, studies that replicate the equity premium puzzle with a Lucas Asset Pricing Model examine the excess returns of a risky security or index relative to those of risk-free assets or treasury bonds. Although virtual currencies resemble the role of money and create an alternative environment for conducting business, it was not until 2016 that cryptocurrencies were unacknowledged by academics. Cryptocurrencies are commonly used as methods of payments, but it is heavily debated whether they truly function as currencies. Since the role cryptocurrency plays is unclear to many, how cryptocurrency is regulated by financial institutions is controversial. Vandezande (2017) claims that it is increasingly important to analyze the behavior of cryptocurrencies as financial tools because there are few explanations for the current behavior of cryptocurrencies as investment tools. He analyzes the extent to which virtual currencies are regulated within the European Union and ascertains that cryptocurrencies have the highest risk among all types of virtual currencies. Although Vandezande (2017) does not include empirical tests, he further maintains that investors are not fully informed about the risk relating to cryptocurrency investments due to the absence of regulatory bodies and the enforcement of protection mechanisms5. He lastly suggests that legal frameworks used for traditional currencies and financial investments are applicable to the various types of virtual currencies and cryptocurrency service providers.

Much of the financial literature contains ambiguous results concerning the behavior of cryptocurrencies. Thus, the debate about whether cryptocurrencies are a speculative investment asset or a currency remains ongoing. Corbet, Meegan, et al. (2018) examine the relationships between cryptocurrencies and other financial assets with the Diebold and Yilmaz methodology6, Barunik and Krehlik methodology7, and a standard Multivariate Generalized Autoregressive Conditional Heteroskedasticity model with dynamic conditional correlations (MVGARCH- DCC) model. They hypothesize that, “cryptocurrency markets, i.e. Bitcoin, Ripple, and Litecoin, are strongly interconnected and demonstrate similar patterns of return and volatility transmission with other assets.”8 To study the return and volatility transmission among Bitcoin, Ripple, and Litecoin and research the excess return and volatility transmission to gold, bond, equities, and the global volatility index (VIX), they measure changes in the correlations of the aforementioned assets’ volatilities and returns. Their findings demonstrate that cryptocurrencies are relatively isolated from market shocks and decoupled from popular financial assets, despite the fact that the performance of each cryptocurrency is correlated to the performance of other cryptocurrencies. Corbet, Meegan, et al. (2018) also find that Bitcoin, Ripple, and Litecoin are highly sensitive to industry regulations and technological malfunctions. Ergo, the interconnectedness among cryptocurrencies indicates that substantial changes in cryptocurrency prices are attributable to speculative activity. These results suggest that cryptocurrencies can be effective tools for portfolio diversification.

Although cryptocurrencies may serve as useful portfolio diversifiers their returns do not behave similarly to standard asset classes.9 Liu and Tsyvinski (2018) investigate whether the cryptocurrency market behaves similarly to the stock market. They do so by determining whether or not the returns of cryptocurrency are compensated by risk factors derived from the stock market and analyzing CAPM alphas, CAPM betas, and Eugene Fama and Kenneth French’s five risk factors. Thereafter, they study the exposure of cryptocurrency returns to the Australian Dollar, Canadian Dollar, Euro, Singaporean Dollar, and UK Pound. Although major national currencies strongly comove with one another, the exposures of all cryptocurrencies to major currencies are not statistically significant. Hence, Liu and Tsyvinski (2018) fail to reject the null hypothesis that cryptocurrency serves as another medium of exchange. They also examine the exposure of cryptocurrency returns to precious metal commodities and test whether or not cryptocurrencies serve as a store of value. Again, they find that the exposure of cryptocurrencies is insignificant. Traditional currencies fulfill three objectives: a unit of account, a store of value, and a medium of exchange. However, the implementation of empirical asset pricing models and the analysis of co-movements among Bitcoin, Ripple, Ethereum, stocks, currencies, commodities, macroeconomic factors, and cryptocurrency market specific factors show that cryptocurrencies can be assessed using simple financial tools, but they behave in a radically different manner than traditional assets. Liu and Tsyvinski (2018) lastly conclude that only cryptocurrency market specific factors including momentum and investor attention consistently explain market returns.

#Model 

#References
