%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: \Users\Jenna\Documents\GitHub\ECON_4008-01-Macro-Modeling\Code\Project\Data\markovchain.xlsx
%    Worksheet: markov chain
%
% Auto-generated by MATLAB on 28-Apr-2019 12:28:52

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 60);

% Specify sheet and range
opts.Sheet = "markov chain";
opts.DataRange = "B2:BI61";

% Specify column names and types
opts.VariableNames = ["VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59", "VarName60", "VarName61"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
stockstatesmarkov = readtable("/Users/Jenna/Documents/GitHub/ECON-4008-Macro-Modeling/Code/Project/Model Final/markovchain.xlsx", opts, "UseExcel", false);

%% Convert to output type
stockstatesmarkov = table2array(stockstatesmarkov);

%% Clear temporary variables
clear  opts

